/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo

type PiggyBankStore struct {
	Name string `json:"name"`
	// The ID of the asset account this piggy bank is connected to.
	AccountId string `json:"account_id"`
	TargetAmount string `json:"target_amount"`
	CurrentAmount string `json:"current_amount,omitempty"`
	// The date you started with this piggy bank.
	StartDate string `json:"start_date,omitempty"`
	// The date you intend to finish saving money.
	TargetDate string `json:"target_date,omitempty"`
	Order int32 `json:"order,omitempty"`
	Active bool `json:"active,omitempty"`
	Notes string `json:"notes,omitempty"`
	// The group ID of the group this object is part of. NULL if no group.
	ObjectGroupId string `json:"object_group_id,omitempty"`
	// The name of the group. NULL if no group.
	ObjectGroupTitle string `json:"object_group_title,omitempty"`
}
