/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo
import (
	"time"
)

type PiggyBankEvent struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	CurrencyId string `json:"currency_id,omitempty"`
	CurrencyCode string `json:"currency_code,omitempty"`
	CurrencySymbol string `json:"currency_symbol,omitempty"`
	CurrencyDecimalPlaces int32 `json:"currency_decimal_places,omitempty"`
	Amount string `json:"amount,omitempty"`
	// The journal associated with the event.
	TransactionJournalId string `json:"transaction_journal_id,omitempty"`
	// The transaction group associated with the event.
	TransactionGroupId string `json:"transaction_group_id,omitempty"`
}
