/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo

type ConfigValueFilter string

// List of ConfigValueFilter
const (
	CONFIGURATIONIS_DEMO_SITE_ConfigValueFilter ConfigValueFilter = "configuration.is_demo_site"
	CONFIGURATIONPERMISSION_UPDATE_CHECK_ConfigValueFilter ConfigValueFilter = "configuration.permission_update_check"
	CONFIGURATIONLAST_UPDATE_CHECK_ConfigValueFilter ConfigValueFilter = "configuration.last_update_check"
	CONFIGURATIONSINGLE_USER_MODE_ConfigValueFilter ConfigValueFilter = "configuration.single_user_mode"
	FIREFLYVERSION_ConfigValueFilter ConfigValueFilter = "firefly.version"
	FIREFLYAPI_VERSION_ConfigValueFilter ConfigValueFilter = "firefly.api_version"
	FIREFLYDEFAULT_LOCATION_ConfigValueFilter ConfigValueFilter = "firefly.default_location"
	FIREFLYACCOUNT_TO_TRANSACTION_ConfigValueFilter ConfigValueFilter = "firefly.account_to_transaction"
	FIREFLYALLOWED_OPPOSING_TYPES_ConfigValueFilter ConfigValueFilter = "firefly.allowed_opposing_types"
	FIREFLYACCOUNT_ROLES_ConfigValueFilter ConfigValueFilter = "firefly.accountRoles"
	FIREFLYVALID_LIABILITIES_ConfigValueFilter ConfigValueFilter = "firefly.valid_liabilities"
	FIREFLYINTEREST_PERIODS_ConfigValueFilter ConfigValueFilter = "firefly.interest_periods"
	FIREFLYENABLE_EXTERNAL_MAP_ConfigValueFilter ConfigValueFilter = "firefly.enable_external_map"
	FIREFLYEXPECTED_SOURCE_TYPES_ConfigValueFilter ConfigValueFilter = "firefly.expected_source_types"
	APPTIMEZONE_ConfigValueFilter ConfigValueFilter = "app.timezone"
)
