/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo
import (
	"time"
)

type WebhookMessage struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// If this message is sent yet.
	Sent bool `json:"sent,omitempty"`
	// If this message has errored out.
	Errored bool `json:"errored,omitempty"`
	// The ID of the webhook this message belongs to.
	WebhookId string `json:"webhook_id,omitempty"`
	// Long UUID string for identification of this webhook message.
	Uuid string `json:"uuid,omitempty"`
	// The actual message that is sent or will be sent as JSON string.
	String_ string `json:"string,omitempty"`
}
