/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo

type InsightTransferEntry struct {
	// This ID is a reference to the original object.
	Id string `json:"id,omitempty"`
	// This is the name of the object.
	Name string `json:"name,omitempty"`
	// The total amount transferred between start date and end date, a number defined as a string, for this asset account.
	Difference string `json:"difference,omitempty"`
	// The total amount transferred between start date and end date, a number as a float, for this asset account. May have rounding errors.
	DifferenceFloat float64 `json:"difference_float,omitempty"`
	// The total amount transferred TO this account between start date and end date, a number defined as a string, for this asset account.
	In string `json:"in,omitempty"`
	// The total amount transferred FROM this account between start date and end date, a number as a float, for this asset account. May have rounding errors.
	InFloat float64 `json:"in_float,omitempty"`
	// The total amount transferred FROM this account between start date and end date, a number defined as a string, for this asset account.
	Out string `json:"out,omitempty"`
	// The total amount transferred TO this account between start date and end date, a number as a float, for this asset account. May have rounding errors.
	OutFloat float64 `json:"out_float,omitempty"`
	// The currency ID of the expenses listed for this account.
	CurrencyId string `json:"currency_id,omitempty"`
	// The currency code of the expenses listed for this account.
	CurrencyCode string `json:"currency_code,omitempty"`
}
