/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo
import (
	"time"
)

type RuleAction struct {
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// The type of thing this action will do. A limited set is possible.
	Type_ string `json:"type"`
	// The accompanying value the action will set, change or update. Can be empty, but for some types this value is mandatory.
	Value string `json:"value"`
	// Order of the action
	Order int32 `json:"order,omitempty"`
	// If the action is active. Defaults to true.
	Active bool `json:"active,omitempty"`
	// When true, other actions will not be fired after this action has fired. Defaults to false.
	StopProcessing bool `json:"stop_processing,omitempty"`
}
