/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo

type TransactionUpdate struct {
	// Whether or not to apply rules when submitting transaction.
	ApplyRules bool `json:"apply_rules,omitempty"`
	// Whether or not to fire the webhooks that are related to this event.
	FireWebhooks bool `json:"fire_webhooks,omitempty"`
	// Title of the transaction if it has been split in more than one piece. Empty otherwise.
	GroupTitle string `json:"group_title,omitempty"`
	Transactions []TransactionSplitUpdate `json:"transactions,omitempty"`
}
