/*
 * Firefly III API v1.5.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * API version: 1.5.4
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ffgo

type MetaPagination struct {
	Total int32 `json:"total,omitempty"`
	Count int32 `json:"count,omitempty"`
	PerPage int32 `json:"per_page,omitempty"`
	CurrentPage int32 `json:"current_page,omitempty"`
	TotalPages int32 `json:"total_pages,omitempty"`
}
